apiVersion: v1
kind: Pod
metadata:
  name: wi-test
  namespace: demo
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: api-sa
  containers:
  - name: azure-cli
    image: mcr.microsoft.com/azure-cli
    command:
    - /bin/sh
    - -c
    - sleep infinity